apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cronjob
  namespace: demo-ns
spec:
  schedule: "17 11 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-cronjob
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
