apiVersion: batch/v1
kind: CronJob
metadata:
  name: deployment-restart-nginx
  namespace: demo-ns
spec:
  concurrencyPolicy: Forbid
  schedule: "52 11 * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 600
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          serviceAccountName: deployment-restart
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/nginx'
