apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-restart
  namespace: demo-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-restart-nginx
subjects:
  - kind: ServiceAccount
    name: deployment-restart # important - the name of the service account
    namespace: demo-ns

