apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-restart-nginx
  namespace: demo-ns
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: ["nginx"]
    verbs: ["get", "patch", "list", "watch"] # extended list of operations
